"""One sentence per rule that the rule must catch (used by tests/test_rule_examples.py).

Rules with min_hits > 1 get an example with that many hits. These also document
what each rule is for, in the same spirit as the example lists of the
predecessor skills.
"""

EXAMPLES = {
    "stock.ieru_deshou": "この方法は有効だと言えるでしょう。",
    "stock.ieru": "結果はおおむね良好と言えます。",
    "stock.nodewa": "まずは小さく始めるのがよいのではないでしょうか。",
    "stock.ikaga": "以上、新機能の紹介でした。いかがでしたか？",
    "stock.zehi_close": "気になった方は、ぜひ一度試してみてください。",
    "stock.matomeru_to": "前の章の続きです。まとめると、準備が八割です。",
    "stock.ketsuron": "結論から言うと、来月の移行は見送ります。",
    "stock.juyou_nowa": "最も重要なのは、毎日続けることです。",
    "stock.juuyou_desu": "記録を残すことが重要です。手順をそろえておくことが大切です。",
    "stock.mitekimashou": "それでは、具体的な手順を見ていきましょう。",
    "stock.ni_tsuite_kaisetsu": "本記事では、設定の手順について解説します。",
    "stock.ichigai": "効果は一概には言えませんが、試す価値はあります。",
    "stock.kagi": "チームの対話が成功の鍵となります。",
    "stock.iu_made": "言うまでもなく、安全が最優先です。",
    "stock.chuumoku": "注目すべきは、処理時間が半分になった点です。",
    "stock.ageraremasu": "原因として設定の誤りが挙げられます。対策としては監視の強化が挙げられます。",
    "inflated.buzz": "業務をシームレスにつなぎ、新たな価値を提供します。",
    "inflated.slop_nouns": "現場の温度感を共有しておきます。",
    "inflated.yakuwari": "この部署は重要な役割を果たしています。",
    "inflated.samazama": "様々な部署から様々な意見が出て、様々な案を比べました。",
    "inflated.hijou_ni": "この機能は非常に便利です。設定も非常に重要です。",
    "inflated.kotoba_dake": "課題を言語化してから次に進みます。",
    "inflated.kakasenai": "今や業務に欠かせない存在になりました。",
    "translationese.dekiru": "画面から設定を変更することができます。",
    "translationese.dekiru_verb": "書類を受け取ることができます。郵送で送ることができます。",
    "translationese.kanten": "コストという観点から見直します。",
    "translationese.ni_totte": "この計画にとって重要な前提です。",
    "translationese.motsu": "この決定は大きな意味を持ちます。",
    "translationese.niyotte": "情報を整理することによって判断が速くなります。",
    "translationese.hokanaranai": "これは時代の変化の表れに他なりません。",
    "translationese.mushoku_shugo": "この結果は需要の変化を示しています。",
    "translationese.okonau": "確認を行います。調整を行います。報告を行います。",
    "template.count_decl": "上達には3つのポイントがあります。",
    "template.ikutsuka": "長持ちさせるには、いくつかのコツがあります。",
    "template.ika_matome": "以下に、主な変更点をまとめました。",
    "template.rhetorical_q": "なぜでしょうか？それは在庫が足りないからです。",
    "template.sorekoso": "これこそが私たちの強みです。",
    "template.closing_offer": "何かご不明な点があれば、お気軽にお聞きください。",
    "template.hope_helpful": "お役に立てれば幸いです。",
    "template.mazu_tsugini": "まず、資料を読みます。\n次に、要点を書き出します。\n最後に、全体を見直します。",
    "format.em_dash": "この機能——つまり自動保存——は標準で動きます。",
    "format.bold": "**手順1**を終えたら**手順2**に進みます。",
    "format.bold_label": "- **速さ**：処理が二倍になります。",
    "format.bold_heading_line": "\n**1. 朝の時間を使う**\n",
    "format.colon_lead": "主な変更点は次のとおり：\n対象は次のとおり：\n",
    "format.heading_in_chat": "## 準備するもの\n材料をそろえます。",
    "format.emoji_bullet": "✅ 申し込みを済ませる",
    "format.emoji": "完成しました🎉 みんなで乾杯🍻",
    "format.arrow_chain": "受付→確認→発送の順に進みます。",
    "format.exclaim": "やりました！ついに完成！本当にうれしい！",
    "format.paren_gloss": "検索拡張生成（Retrieval Augmented Generation）と大規模言語モデル（Large Language Model）を使います。",
    "contrast.dewanaku": "量ではなく質を見ます。速さではなく正確さを優先します。",
    "sycophancy.great_q": "素晴らしい質問ですね！",
    "sycophancy.empathy": "迷いますよね。まずは条件を整理しましょう。",
    "sycophancy.kashikomari": "かしこまりました！以下に案をまとめます。",
    "stock.chatbot_residue": "他にご質問があれば、何でも聞いてください。",
    "stock.cutoff": "私の知識のカットオフ時点の情報です。",
    "stock.false_nuance": "より正確には、条件によって結果が変わります。",
    "stock.filler": "周知の通り、締め切りは月末です。",
    "stock.empty_optimism": "今後の展開に期待が高まります。",
    "stock.throat_clearing": "正直に言うと、この案には反対です。",
    "stock.pseudo_insight": "誰も教えてくれない節約のコツを紹介します。",
    "stock.lexicon": "現代社会において、情報の扱いは難しくなっています。",
    "stock.mazu_saisho": "まず最初に、電源を入れます。",
    "inflated.hype": "革命的な機能を搭載しました。",
    "inflated.significance": "業界の歴史的な転換点となりました。",
    "inflated.teki_chain": "戦略的かつ効率的な方法で、積極的に取り組みます。",
    "translationese.ing_surface": "売上の伸びは市場の変化を反映しており、今後も続く見込みです。",
    "translationese.vague_source": "専門家によると、来年は値上がりします。",
    "translationese.stiff": "本書が皆様の一助となれば幸いです。",
    "template.colon_reveal": "結論：今月は見送りです。",
    "format.info_prefix_bold": "**注意**：電源を切ってから作業します。",
    "format.ai_leakage": "出典はこちらです。:contentReference[oaicite:0]",
    "format.halfwidth_mark": "今日はいい天気!明日も晴れるかな?",
    "contrast.nominarazu": "これは単なる道具ではありません。",
    "stock.stacked_closing": "ご確認のほどよろしくお願いいたします。お気軽にお問い合わせください。今後ともよろしくお願いいたします。",
    "template.sns_cta": "皆さんの意見をぜひコメントで教えてください！",
    "template.sns_question": "皆さんにとって理想の働き方とは何ですか？ぜひコメントで教えてください！",
    "inflated.marketing_cliche": "素材と技が織りなす至福のひとときをどうぞ。",
    "inflated.pr_cliche": "働き方の未来を共に創ってまいります。",
    "inflated.pr_formula": "これからもお客様に寄り添います。地域の発展に貢献してまいります。",
    "stock.both_sides": "どちらにもメリットとデメリットがあります。",
    "translationese.enable": "この仕組みが高速な検索を可能にします。",
    "translationese.anata": "あなたのチームに合う方法を選びましょう。",
    "translationese.let_me_know": "質問があれば遠慮なく私に知らせてください。",
    "stock.evaluative_cliche": "今回の出張は非常に有意義な機会となりました。",
    "stock.era_opening": "変化の激しい時代において、学び続けることが求められます。",
    "template.anata_e": "そんなあなたへ、新しいプランのご案内です。",
    "template.before_after": "「困った」を「できた」に変えるアプリです。",
    "format.wave_heading": "＼新商品が登場／",
    "stock.over_keigo": "確認させていただきます。送付させていただきます。連絡させていただきます。",
    "translationese.double_negative": "使えないことはない。分からないわけではない。",
}
